CREATE TABLE ARTISTE (
    idArtiste INTEGER NOT NULL PRIMARY KEY,
    nom VARCHAR(50),
    code pays CHAR(2) REFERENCES PAYS ON DELETE SET NULL, 
    naissance DATE,
    type CHAR(1) NOT NULL
);

CREATE TABLE FILM (
    idFilm INTEGER NOT NULL PRIMARY KEY,
    titre VARCHAR(100) NOT NULL,
    annee INTEGER,
    genre VARCHAR(30),
    idRealisateur INTEGER REFERENCES ARTISTE,
    codePays CHAR(2) REFERENCES PAYS ON DELETE SET NULL
);

CREATE TABLE ALBUM (
    idAlbum INTEGER NOT NULL PRIMARY KEY,
    titre VARCHAR(100) NOT NULL,
    annee INTEGER,
    genre VARCHAR(30),
    idArtistePrincipal INTEGER REFERENCES ARTISTE,
    label VARCHAR(50)
);

CREATE TABLE UTILISATEUR (
    idUser INTEGER NOT NULL PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    age INTEGER,
    codepays CHAR(2) REFERENCES PAYS ON DELETE SET NULL
);

CREATE TABLE AVIS_FILM (
    idAvis INTEGER NOT NULL PRIMARY KEY,
    idUser INTEGER NOT NULL REFERENCES UTILISATEUR,
    idFilm INTEGER NOT NULL REFERENCES FILM,
    note INTEGER NOT NULL,
    commentaire VARCHAR(255),
    dateAvis DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE AVIS_ALBUM (
    idAvis INTEGER NOT NULL PRIMARY KEY,
    idUser INTEGER NOT NULL REFERENCES UTILISATEUR, 
    idAlbum INTEGER NOT NULL REFERENCES ALBUM,
    note INTEGER NOT NULL,
    commentaire VARCHAR(255),
    dateAvis DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE PAYS ( 
    codePays CHAR (2) NOT NULL PRIMARY KEY,
    nom VARCHAR (40) NOT NULL
);

CREATE TABLE PARTICIPE_FILM (
    idArtiste INTEGER NOT NULL REFERENCES ARTISTE,
    idFilm INTEGER NOT NULL REFERENCES FILM,
    role VARCHAR(30) NOT NULL,
    PRIMARY KEY (idArtiste, idFilm)
);

CREATE TABLE HISTORIQUE_PROPOSITION_FILM (
    idUser INTEGER NOT NULL REFERENCES UTILISATEUR,
    idFilm INTEGER NOT NULL REFERENCES FILM,
    dateProposee DATE NOT NULL,
    PRIMARY KEY (idUser, idFilm)
);

CREATE TABLE HISTORIQUE_PROPOSITION_ALBUM (
    idUser INTEGER NOT NULL REFERENCES UTILISATEUR,
    idAlbum INTEGER NOT NULL REFERENCES ALBUM,
    dateProposee DATE NOT NULL,
    PRIMARY KEY (idUser, idAlbum)
);
